.nlp.loadfile:{-1"Loading ",x;system"l nlp/",x;}
.nlp.loadfile"utils.q"
.nlp.loadfile"regex.q"
.nlp.loadfile"sent.q"
.nlp.loadfile"parser.q"
.nlp.loadfile"time.q"
.nlp.loadfile"date.q"
.nlp.loadfile"email.q"
.nlp.loadfile"cluster.q"
.nlp.loadfile"nlp.q"
